# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course'),
    ]

    operations = [
    ]
